Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "192.168.0.63"
  config.vm.hostname = "cassandra"
  config.vm.provision "shell", path: "cassandra.sh", privileged: false
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
end
