---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[DICETraffic::default]

  - name: collectors
    run_list:
      - recipe[DICETraffic::default]
      - recipe[DICETraffic::collectors]
    attributes:
      DICE-BigData-Traffic:
        config:
          kafka_host: mykafka.local.lan:9092
          bt_sensors:
            timon_username: blueadmin
            timon_password: toothsword
